Repository micronaut-projects/micronaut-hibernate-validator, pull requests merged in 2023-07, with the labels that each got.

#317 [hibernate-validator] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#323 [hibernate-validator] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#326 Hibernate Validator to Core 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#329 Hibernate Validator no Milestones
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#333 Hibernate-validator managed version and api Gradle configuration
  gradle/libs.versions.toml
  hibernate-validator/build.gradle
  hibernate-validator/build.gradle.kts
Labels: relates-to: build, type: improvement

#337 [hibernate-validator] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
Labels: relates-to: build
